debug: false
seed: 42
run:
  name: "train_unet_${now:%Y-%m-%d_%H-%M-%S}"

# Model configuration
model:
  trained_model_path: "data/trainings/train_unet_2024-09-05_19-12-03/models/best_model.pth"
  number_of_input_channels: 16
  number_of_classes: 1
  activation_fn_name: "relu"
  num_encoder_decoder_blocks: 4
  use_batchnorm: true

# Data configuration
data:
  provinces:
    - "NL"
    - "PE"
    - "NS"
    - "NB"
    - "QC"
    - "ON"
    - "MB"
    - "SK"
    - "AB"
    - "BC"
 input_data_periods_folders_paths:
    - "/Users/sakshamj/Desktop/fire/WildfirePrediction/data/input_data/2023_2023"  # Path to 2023 input data folder
    - "/Users/sakshamj/Desktop/fire/WildfirePrediction/data/input_data/2024_2024"  # Path to 2024 input data folder

  # Paths for target data (list of corresponding directories for each period or range)
  target_periods_folders_paths:
    - "/Users/sakshamj/Desktop/fire/WildfirePrediction/data/target_data/2023_2023"  # Path to 2023 target data folder
    - "/Users/sakshamj/Desktop/fire/WildfirePrediction/data/target_data/2024_2024"  # Path to 2024 target data folder
  target_srid: 3978
  split_info_file_path: 'data/splits/data_split_info.json'
  input_data_folder_path: '/Users/sakshamj/Desktop/fire/WildfirePrediction/data/predict/test/2023/'
  input_data_no_data_value: -32768.0
  input_data_new_no_data_value: 0.0
  data_loading_num_workers: 4
  input_data_indexes_to_remove: []

# Prediction configuration
predict:
  batch_size: 64
  convert_model_output_to_probabilities: true
  output_folder_path: 'data/predictions_outputs/'  # Correct place for output path for predictions


